import type {
  BaitDefinition,
  BoatDefinition,
  FishSpecies,
  GameCatalog,
  LocationDefinition,
  LureDefinition,
  RodDefinition,
} from "./contracts";

const ONTARIO_FISH_GUIDE = {
  name: "Ontario Learn to Fish guide",
  url: "https://www.ontario.ca/page/learn-fish-guide",
};

const LAKE_ONTARIO_OBJECTIVES = {
  name: "Fish Community Objectives for Lake Ontario",
  url: "https://files.ontario.ca/mnrf-fish-community-objectives-lake-ontario-en-2019-10-02.pdf",
};

const locations: LocationDefinition[] = [
  {
    id: "willow-pond",
    name: "Willow Pond",
    description: "A calm, weedy starter pond where light tackle and patient hands are enough.",
    riskReason: "Shallow water and smaller fish keep strain on a suitable rod low.",
    riskBand: "low",
    requiredBoatId: "shore-fishing",
    expectedValueMinCoins: 6,
    expectedValueMaxCoins: 90,
    fishIds: ["yellow-perch", "pumpkinseed", "rock-bass", "bluegill", "golden-shiner", "smallmouth-bass"],
  },
  {
    id: "mill-creek",
    name: "Mill Creek",
    description: "A winding public creek where pools, undercut banks, and riffles reward a careful cast.",
    riskReason: "Most fish are modest, but a surprise trout can test the starter rod.",
    riskBand: "low",
    requiredBoatId: "shore-fishing",
    expectedValueMinCoins: 7,
    expectedValueMaxCoins: 120,
    fishIds: ["creek-chub", "white-sucker", "brown-bullhead", "yellow-bullhead", "rock-bass", "brook-trout"],
  },
  {
    id: "cedar-marsh",
    name: "Cedar Marsh",
    description: "A maze of lily pads and flooded timber where patient casts uncover ambush predators.",
    riskReason: "Flooded timber and strong bottom-feeders can load a light rod quickly.",
    riskBand: "moderate",
    requiredBoatId: "rowboat",
    expectedValueMinCoins: 18,
    expectedValueMaxCoins: 620,
    fishIds: ["black-crappie", "white-crappie", "common-carp", "bowfin", "freshwater-drum", "longnose-gar", "shorthead-redhorse"],
  },
  {
    id: "pinewater-lake",
    name: "Pinewater Lake",
    description: "Cooler water and deeper structure bring stronger fish and better opportunities.",
    riskReason: "Deeper water creates longer fights, and the larger fish can exceed starter tackle.",
    riskBand: "moderate",
    requiredBoatId: "rowboat",
    expectedValueMinCoins: 24,
    expectedValueMaxCoins: 520,
    fishIds: ["smallmouth-bass", "largemouth-bass", "walleye", "sauger", "northern-pike", "channel-catfish", "white-sucker"],
  },
  {
    id: "granite-reservoir",
    name: "Granite Reservoir",
    description: "A clear shield-country reservoir of rocky points, cold basins, and submerged ridges.",
    riskReason: "Cold-water fish run deeper and trophy pike can exceed medium tackle.",
    riskBand: "moderate",
    requiredBoatId: "fishing-skiff",
    expectedValueMinCoins: 38,
    expectedValueMaxCoins: 900,
    fishIds: ["smallmouth-bass", "walleye", "northern-pike", "brook-trout", "splake", "burbot", "lake-whitefish"],
  },
  {
    id: "silverpine-river",
    name: "Silverpine River",
    description: "A broad cold river with tailouts, boulder gardens, and deep bends beneath the pines.",
    riskReason: "Fast current magnifies every run and makes salmonids harder to control.",
    riskBand: "moderate",
    requiredBoatId: "fishing-skiff",
    expectedValueMinCoins: 42,
    expectedValueMaxCoins: 1100,
    fishIds: ["brook-trout", "rainbow-trout", "brown-trout", "smallmouth-bass", "sauger", "mooneye"],
  },
  {
    id: "lake-greywater",
    name: "Lake Greywater",
    description: "A deep Great Lakes-inspired water where serious tackle meets trophy fish.",
    riskReason: "Trophy fish and open-water runs can overload a rod before you land them.",
    riskBand: "high",
    requiredBoatId: "cuddy-cabin",
    expectedValueMinCoins: 85,
    expectedValueMaxCoins: 2600,
    fishIds: ["lake-trout", "chinook-salmon", "coho-salmon", "walleye", "northern-pike", "muskellunge", "lake-whitefish", "cisco", "rainbow-smelt", "burbot"],
  },
  {
    id: "northwind-channel",
    name: "Northwind Channel",
    description: "Wind-driven current funnels baitfish past reefs, river mouths, and steep blue-water edges.",
    riskReason: "Large migratory fish use the current, producing long fights far from shelter.",
    riskBand: "high",
    requiredBoatId: "cuddy-cabin",
    expectedValueMinCoins: 110,
    expectedValueMaxCoins: 3600,
    fishIds: ["walleye", "northern-pike", "lake-trout", "rainbow-trout", "brown-trout", "burbot", "atlantic-salmon", "pink-salmon", "american-eel"],
  },
  {
    id: "superior-reach",
    name: "Superior Reach",
    description: "A vast northern reach of cold open water, sheer drop-offs, and remote spawning shoals.",
    riskReason: "Heavy salmon, trout, and ancient giants demand purpose-built Great Lakes tackle.",
    riskBand: "high",
    requiredBoatId: "great-lakes-cruiser",
    expectedValueMinCoins: 180,
    expectedValueMaxCoins: 6200,
    fishIds: ["lake-trout", "chinook-salmon", "coho-salmon", "atlantic-salmon", "pink-salmon", "lake-whitefish", "burbot", "lake-sturgeon", "muskellunge"],
  },
  {
    id: "stormglass-basin",
    name: "Stormglass Basin",
    description: "The end of the chart: black water, towering swells, and trophy fish rarely seen elsewhere.",
    riskReason: "Almost every encounter can overpower ordinary lake gear, and record fish are genuinely dangerous.",
    riskBand: "high",
    requiredBoatId: "expedition-vessel",
    expectedValueMinCoins: 300,
    expectedValueMaxCoins: 12000,
    fishIds: ["muskellunge", "lake-sturgeon", "chinook-salmon", "lake-trout", "burbot", "american-eel", "quillback"],
  },
];

const boats: BoatDefinition[] = [
  {
    id: "shore-fishing",
    name: "Shore Fishing",
    description: "A sturdy bank-side setup for Willow Pond.",
    tier: 1,
    priceCoins: 0,
    unlocksLocationIds: ["willow-pond", "mill-creek"],
  },
  {
    id: "rowboat",
    name: "Rowboat",
    description: "Reach the reed beds of Cedar Marsh and the quiet coves of Pinewater Lake.",
    tier: 2,
    priceCoins: 450,
    unlocksLocationIds: ["willow-pond", "mill-creek", "cedar-marsh", "pinewater-lake"],
  },
  {
    id: "fishing-skiff",
    name: "Fishing Skiff",
    description: "A stable casting platform for reservoirs and broad rivers.",
    tier: 3,
    priceCoins: 1800,
    unlocksLocationIds: ["willow-pond", "mill-creek", "cedar-marsh", "pinewater-lake", "granite-reservoir", "silverpine-river"],
  },
  {
    id: "cuddy-cabin",
    name: "Cuddy Cabin",
    description: "Sheltered Great Lakes capability for rough crossings and long sessions offshore.",
    tier: 4,
    priceCoins: 6000,
    unlocksLocationIds: ["lake-greywater", "northwind-channel"],
  },
  {
    id: "great-lakes-cruiser",
    name: "Great Lakes Cruiser",
    description: "A powerful deep-water boat equipped for remote reefs and serious trolling.",
    tier: 5,
    priceCoins: 16000,
    unlocksLocationIds: ["superior-reach"],
  },
  {
    id: "expedition-vessel",
    name: "Expedition Vessel",
    description: "The ultimate all-weather platform for the most distant and dangerous water.",
    tier: 6,
    priceCoins: 42000,
    unlocksLocationIds: ["stormglass-basin"],
  },
];

const rods: RodDefinition[] = [
  {
    id: "starter-fiberglass",
    name: "Starter Fiberglass",
    description: "Forgiving and reliable for small pond fish.",
    priceCoins: 0,
    strength: 1,
    control: 1,
    maxFishWeightKg: 2.5,
    breakResistance: 0.995,
    catchZoneBonus: 0.02,
  },
  {
    id: "reedline-composite",
    name: "Reedline Composite",
    description: "A light but capable upgrade for creek trout, crappie, and small bass.",
    priceCoins: 240,
    strength: 2,
    control: 1.1,
    maxFishWeightKg: 4.5,
    breakResistance: 0.994,
    catchZoneBonus: 0.04,
  },
  {
    id: "medium-heavy-carbon",
    name: "Medium-Heavy Carbon",
    description: "A responsive rod for bass, walleye, and pike.",
    priceCoins: 650,
    strength: 2,
    control: 1.18,
    maxFishWeightKg: 8,
    breakResistance: 0.99,
    catchZoneBonus: 0.06,
  },
  {
    id: "river-graphite",
    name: "River Graphite",
    description: "Quick recovery and extra backbone for current, trout, and hard-running walleye.",
    priceCoins: 1500,
    strength: 3,
    control: 1.26,
    maxFishWeightKg: 12,
    breakResistance: 0.991,
    catchZoneBonus: 0.08,
  },
  {
    id: "lake-heavy",
    name: "Lake Heavy",
    description: "Built for powerful fish and long fights in open water.",
    priceCoins: 3000,
    strength: 4,
    control: 1.34,
    maxFishWeightKg: 18,
    breakResistance: 0.985,
    catchZoneBonus: 0.1,
  },
  {
    id: "trolling-pro",
    name: "Trolling Pro",
    description: "A forgiving offshore rod that absorbs the first violent run of a large salmon.",
    priceCoins: 6800,
    strength: 5,
    control: 1.42,
    maxFishWeightKg: 28,
    breakResistance: 0.988,
    catchZoneBonus: 0.12,
  },
  {
    id: "great-lakes-power",
    name: "Great Lakes Power",
    description: "Heavy deep-water tackle for trophy trout, sturgeon, and open-water predators.",
    priceCoins: 14800,
    strength: 6,
    control: 1.5,
    maxFishWeightKg: 45,
    breakResistance: 0.987,
    catchZoneBonus: 0.14,
  },
  {
    id: "titanium-muskie",
    name: "Titanium Muskie",
    description: "Endgame tackle built to control the heaviest freshwater fish in the catalogue.",
    priceCoins: 32000,
    strength: 7,
    control: 1.58,
    maxFishWeightKg: 75,
    breakResistance: 0.986,
    catchZoneBonus: 0.16,
  },
];

const lures: LureDefinition[] = [
  {
    id: "copper-spinner",
    name: "Copper Spinner",
    description: "A dependable all-purpose lure for shallow water.",
    priceCoins: 40,
    maximumDurability: 10,
    catchZoneBonus: 0.02,
    difficultyModifier: 0,
    preferredFishIds: ["yellow-perch", "pumpkinseed", "rock-bass", "bluegill", "smallmouth-bass"],
  },
  {
    id: "silver-spinner",
    name: "Silver Spinner",
    description: "A bright spinner that draws active predators.",
    priceCoins: 120,
    maximumDurability: 12,
    catchZoneBonus: 0.04,
    difficultyModifier: 0.03,
    preferredFishIds: ["smallmouth-bass", "largemouth-bass", "walleye", "northern-pike"],
  },
  {
    id: "marsh-jig",
    name: "Marsh Jig",
    description: "A compact jig that slips through reeds and lily pads without spooking cover fish.",
    priceCoins: 70,
    maximumDurability: 11,
    catchZoneBonus: 0.03,
    difficultyModifier: 0.015,
    preferredFishIds: ["black-crappie", "bowfin", "yellow-perch"],
  },
  {
    id: "deep-diver",
    name: "Deep Diver",
    description: "A hard-running lure for cold, deep-water fish.",
    priceCoins: 300,
    maximumDurability: 15,
    catchZoneBonus: 0.06,
    difficultyModifier: 0.06,
    preferredFishIds: ["lake-trout", "chinook-salmon", "coho-salmon", "muskellunge"],
  },
  {
    id: "micro-spoon",
    name: "Micro Spoon",
    description: "A fluttering little spoon for creek fish, panfish, and cautious trout.",
    priceCoins: 65,
    maximumDurability: 12,
    catchZoneBonus: 0.035,
    difficultyModifier: 0.01,
    preferredFishIds: ["creek-chub", "golden-shiner", "brook-trout", "black-crappie", "white-crappie"],
  },
  {
    id: "topwater-frog",
    name: "Topwater Frog",
    description: "A weedless surface lure for bass, bowfin, pike, and gar in dense cover.",
    priceCoins: 190,
    maximumDurability: 13,
    catchZoneBonus: 0.045,
    difficultyModifier: 0.045,
    preferredFishIds: ["largemouth-bass", "bowfin", "northern-pike", "longnose-gar"],
  },
  {
    id: "tube-jig",
    name: "Tube Jig",
    description: "A bottom-hopping soft plastic for rocky bass, walleye, and river fish.",
    priceCoins: 240,
    maximumDurability: 16,
    catchZoneBonus: 0.055,
    difficultyModifier: 0.025,
    preferredFishIds: ["smallmouth-bass", "walleye", "sauger", "shorthead-redhorse", "freshwater-drum"],
  },
  {
    id: "river-fly",
    name: "River Fly",
    description: "A durable streamer pattern for trout and salmon feeding in moving water.",
    priceCoins: 420,
    maximumDurability: 18,
    catchZoneBonus: 0.075,
    difficultyModifier: 0.04,
    preferredFishIds: ["brook-trout", "rainbow-trout", "brown-trout", "atlantic-salmon", "mooneye"],
  },
  {
    id: "trolling-spoon",
    name: "Trolling Spoon",
    description: "A wide-wobbling spoon tuned for lake trout, steelhead, and open-water salmon.",
    priceCoins: 760,
    maximumDurability: 20,
    catchZoneBonus: 0.09,
    difficultyModifier: 0.06,
    preferredFishIds: ["lake-trout", "rainbow-trout", "chinook-salmon", "coho-salmon", "pink-salmon"],
  },
  {
    id: "salmon-flasher",
    name: "Salmon Flasher",
    description: "An offshore attractor that calls powerful salmon from deep blue water.",
    priceCoins: 1450,
    maximumDurability: 24,
    catchZoneBonus: 0.11,
    difficultyModifier: 0.08,
    preferredFishIds: ["chinook-salmon", "coho-salmon", "atlantic-salmon", "pink-salmon"],
  },
  {
    id: "giant-bucktail",
    name: "Giant Bucktail",
    description: "A massive high-resistance lure made for muskellunge and other apex predators.",
    priceCoins: 2600,
    maximumDurability: 28,
    catchZoneBonus: 0.13,
    difficultyModifier: 0.1,
    preferredFishIds: ["muskellunge", "lake-sturgeon", "northern-pike", "longnose-gar"],
  },
];

const baits: BaitDefinition[] = [
  {
    id: "worm",
    name: "Worm",
    description: "A simple, reliable bait that keeps a new angler fishing.",
    priceCoins: 8,
    attraction: 1,
    fishIds: ["yellow-perch", "pumpkinseed", "rock-bass", "bluegill", "yellow-bullhead", "smallmouth-bass", "channel-catfish"],
  },
  {
    id: "sweet-corn",
    name: "Sweet Corn",
    description: "A bright, patient bait for marsh panfish and hungry bottom-feeders.",
    priceCoins: 12,
    attraction: 1.08,
    fishIds: ["black-crappie", "white-crappie", "golden-shiner", "creek-chub", "common-carp", "freshwater-drum", "shorthead-redhorse"],
  },
  {
    id: "minnow",
    name: "Minnow",
    description: "Live bait that attracts bass, walleye, and pike.",
    priceCoins: 20,
    attraction: 1.2,
    fishIds: ["yellow-perch", "rock-bass", "black-crappie", "white-crappie", "rainbow-smelt", "smallmouth-bass", "largemouth-bass", "walleye", "sauger", "northern-pike", "lake-trout", "brook-trout", "rainbow-trout", "brown-trout", "splake", "mooneye"],
  },
  {
    id: "crayfish",
    name: "Crayfish",
    description: "A meaty bait for hard-fighting bass and catfish.",
    priceCoins: 28,
    attraction: 1.24,
    fishIds: ["rock-bass", "smallmouth-bass", "largemouth-bass", "channel-catfish", "walleye", "sauger", "bowfin", "longnose-gar"],
  },
  {
    id: "premium-minnow",
    name: "Premium Minnow",
    description: "A carefully selected minnow for cold-water predators.",
    priceCoins: 55,
    attraction: 1.5,
    fishIds: ["walleye", "sauger", "northern-pike", "lake-trout", "chinook-salmon", "coho-salmon", "muskellunge", "atlantic-salmon", "pink-salmon", "lake-whitefish", "cisco"],
  },
  {
    id: "nightcrawler",
    name: "Nightcrawler",
    description: "A large lively worm that appeals to river fish and larger bottom-feeders.",
    priceCoins: 18,
    attraction: 1.16,
    fishIds: ["white-sucker", "brown-bullhead", "yellow-bullhead", "shorthead-redhorse", "channel-catfish", "freshwater-drum", "mooneye", "quillback"],
  },
  {
    id: "leech",
    name: "Leech",
    description: "A natural presentation for walleye, bass, trout, and cool-water predators.",
    priceCoins: 32,
    attraction: 1.32,
    fishIds: ["white-sucker", "smallmouth-bass", "largemouth-bass", "walleye", "sauger", "brook-trout", "rainbow-trout", "brown-trout", "burbot"],
  },
  {
    id: "dough-ball",
    name: "Dough Ball",
    description: "A sweet, slow-fishing bait for carp, suckers, buffalo-like fish, and bullheads.",
    priceCoins: 24,
    attraction: 1.22,
    fishIds: ["common-carp", "white-sucker", "brown-bullhead", "shorthead-redhorse", "quillback"],
  },
  {
    id: "salmon-egg",
    name: "Salmon Egg",
    description: "A bright drifting bait for trout and salmon in cold rivers.",
    priceCoins: 46,
    attraction: 1.42,
    fishIds: ["brook-trout", "rainbow-trout", "brown-trout", "atlantic-salmon", "pink-salmon"],
  },
  {
    id: "cut-bait",
    name: "Cut Bait",
    description: "Oily pieces that draw large catfish, eel, burbot, gar, and sturgeon.",
    priceCoins: 70,
    attraction: 1.58,
    fishIds: ["channel-catfish", "bowfin", "burbot", "american-eel", "longnose-gar", "lake-sturgeon"],
  },
  {
    id: "lake-smelt",
    name: "Lake Smelt",
    description: "Cold-water forage reserved for valuable trout, salmon, and trophy predators.",
    priceCoins: 105,
    attraction: 1.78,
    fishIds: ["lake-trout", "chinook-salmon", "coho-salmon", "atlantic-salmon", "pink-salmon", "muskellunge", "burbot"],
  },
  {
    id: "spawn-sack",
    name: "Spawn Sack",
    description: "Premium roe for selective trophy trout and migratory salmon.",
    priceCoins: 165,
    attraction: 2,
    fishIds: ["rainbow-trout", "brown-trout", "chinook-salmon", "coho-salmon", "atlantic-salmon", "pink-salmon", "lake-sturgeon"],
  },
];

function fish(input: Omit<FishSpecies, "source"> & { source?: FishSpecies["source"] }): FishSpecies {
  return { ...input, source: input.source ?? ONTARIO_FISH_GUIDE };
}

type ProgressionFishInput = Omit<FishSpecies, "source" | "movementProfile"> & {
  fightDurationSeconds: number;
  source?: FishSpecies["source"];
};

function progressionFish(input: ProgressionFishInput): FishSpecies {
  const { fightDurationSeconds, ...species } = input;
  const difficulty = species.difficulty;
  return fish({
    ...species,
    movementProfile: {
      speed: Number((0.24 + difficulty * 0.62).toFixed(2)),
      acceleration: Number((0.16 + difficulty * 0.84).toFixed(2)),
      directionChangeFrequency: Number((0.22 + difficulty * 0.58).toFixed(2)),
      unpredictability: Number((0.12 + difficulty * 0.62).toFixed(2)),
      fightDurationSeconds,
    },
  });
}

const fishSpecies: FishSpecies[] = [
  fish({
    id: "yellow-perch",
    commonName: "Yellow Perch",
    scientificName: "Perca flavescens",
    description: "A schooling freshwater fish often found around weeds and gentle structure.",
    habitat: "Shallow weeds, sandy shoals, and quiet lake edges.",
    nativeRange: "Freshwater systems across the Great Lakes and much of eastern North America.",
    minimumWeightKg: 0.05,
    typicalWeightKg: 0.25,
    maximumWeightKg: 1.9,
    minimumLengthCm: 10,
    typicalLengthCm: 25,
    maximumLengthCm: 50,
    rarity: "common",
    baseValueCoins: 12,
    difficulty: 0.16,
    movementProfile: { speed: 0.28, acceleration: 0.18, directionChangeFrequency: 0.24, unpredictability: 0.12, fightDurationSeconds: 10 },
    acceptedBaitIds: ["worm", "minnow"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond", "mill-creek"],
  }),
  fish({
    id: "pumpkinseed",
    commonName: "Pumpkinseed",
    scientificName: "Lepomis gibbosus",
    description: "A brightly marked sunfish that prefers cover, plants, and calm water.",
    habitat: "Vegetated ponds, quiet bays, and protected lake margins.",
    nativeRange: "Freshwater systems of eastern North America, including the Great Lakes.",
    minimumWeightKg: 0.04,
    typicalWeightKg: 0.18,
    maximumWeightKg: 0.8,
    minimumLengthCm: 8,
    typicalLengthCm: 18,
    maximumLengthCm: 30,
    rarity: "common",
    baseValueCoins: 10,
    difficulty: 0.12,
    movementProfile: { speed: 0.24, acceleration: 0.16, directionChangeFrequency: 0.3, unpredictability: 0.14, fightDurationSeconds: 9 },
    acceptedBaitIds: ["worm"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond"],
  }),
  fish({
    id: "rock-bass",
    commonName: "Rock Bass",
    scientificName: "Ambloplites rupestris",
    description: "A stocky bass that holds close to rocks, logs, and shaded cover.",
    habitat: "Rocky shorelines, submerged timber, and clear quiet water.",
    nativeRange: "Eastern and central North American freshwater systems.",
    minimumWeightKg: 0.06,
    typicalWeightKg: 0.22,
    maximumWeightKg: 0.9,
    minimumLengthCm: 10,
    typicalLengthCm: 20,
    maximumLengthCm: 35,
    rarity: "common",
    baseValueCoins: 16,
    difficulty: 0.2,
    movementProfile: { speed: 0.32, acceleration: 0.25, directionChangeFrequency: 0.26, unpredictability: 0.18, fightDurationSeconds: 11 },
    acceptedBaitIds: ["worm", "minnow", "crayfish"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond", "mill-creek"],
  }),
  fish({
    id: "bluegill",
    commonName: "Bluegill",
    scientificName: "Lepomis macrochirus",
    description: "A common sunfish that feeds around vegetation and shallow cover.",
    habitat: "Warm, weedy shallows and protected freshwater coves.",
    nativeRange: "Central and eastern North American freshwater systems.",
    minimumWeightKg: 0.04,
    typicalWeightKg: 0.2,
    maximumWeightKg: 0.9,
    minimumLengthCm: 8,
    typicalLengthCm: 18,
    maximumLengthCm: 30,
    rarity: "common",
    baseValueCoins: 11,
    difficulty: 0.14,
    movementProfile: { speed: 0.26, acceleration: 0.19, directionChangeFrequency: 0.28, unpredictability: 0.15, fightDurationSeconds: 9 },
    acceptedBaitIds: ["worm"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond"],
  }),
  fish({
    id: "black-crappie",
    commonName: "Black Crappie",
    scientificName: "Pomoxis nigromaculatus",
    description: "A speckled panfish that gathers beneath shade, reeds, and submerged branches.",
    habitat: "Clear, quiet bays, weed lines, and brushy cover.",
    nativeRange: "Great Lakes and freshwater systems across central and eastern North America.",
    minimumWeightKg: 0.04,
    typicalWeightKg: 0.25,
    maximumWeightKg: 1.9,
    minimumLengthCm: 8,
    typicalLengthCm: 22,
    maximumLengthCm: 50,
    rarity: "common",
    baseValueCoins: 24,
    difficulty: 0.25,
    movementProfile: { speed: 0.3, acceleration: 0.24, directionChangeFrequency: 0.4, unpredictability: 0.2, fightDurationSeconds: 12 },
    acceptedBaitIds: ["worm", "sweet-corn", "minnow"],
    preferredLureIds: ["copper-spinner", "marsh-jig"],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "common-carp",
    commonName: "Common Carp",
    scientificName: "Cyprinus carpio",
    description: "A wary, broad-shouldered bottom-feeder that makes shallow marsh water feel much deeper.",
    habitat: "Muddy flats, warm bays, and slow water around soft-bottom structure.",
    nativeRange: "Introduced throughout Ontario and established in Great Lakes waters.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 4,
    maximumWeightKg: 20,
    minimumLengthCm: 25,
    typicalLengthCm: 65,
    maximumLengthCm: 120,
    rarity: "uncommon",
    baseValueCoins: 95,
    difficulty: 0.58,
    movementProfile: { speed: 0.42, acceleration: 0.78, directionChangeFrequency: 0.35, unpredictability: 0.45, fightDurationSeconds: 30 },
    acceptedBaitIds: ["worm", "sweet-corn"],
    preferredLureIds: [],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "bowfin",
    commonName: "Bowfin",
    scientificName: "Amia calva",
    description: "An ancient ambush predator that surges from heavy cover with surprising power.",
    habitat: "Warm, weedy backwaters, marsh channels, and flooded timber.",
    nativeRange: "Great Lakes basin and freshwater systems of eastern and central North America.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 1.3,
    maximumWeightKg: 5.5,
    minimumLengthCm: 25,
    typicalLengthCm: 55,
    maximumLengthCm: 90,
    rarity: "uncommon",
    baseValueCoins: 90,
    difficulty: 0.68,
    movementProfile: { speed: 0.62, acceleration: 0.78, directionChangeFrequency: 0.5, unpredictability: 0.48, fightDurationSeconds: 26 },
    acceptedBaitIds: ["minnow", "crayfish", "cut-bait"],
    preferredLureIds: ["marsh-jig", "silver-spinner"],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "freshwater-drum",
    commonName: "Freshwater Drum",
    scientificName: "Aplodinotus grunniens",
    description: "A patient bottom-feeder with a deep-bodied pull and a distinctive drumming call.",
    habitat: "Rocky shoals, sandy flats, and deep channels with moving water.",
    nativeRange: "Great Lakes and freshwater systems across central and eastern North America.",
    minimumWeightKg: 0.15,
    typicalWeightKg: 2.5,
    maximumWeightKg: 12,
    minimumLengthCm: 20,
    typicalLengthCm: 55,
    maximumLengthCm: 100,
    rarity: "uncommon",
    baseValueCoins: 70,
    difficulty: 0.5,
    movementProfile: { speed: 0.38, acceleration: 0.64, directionChangeFrequency: 0.28, unpredictability: 0.35, fightDurationSeconds: 24 },
    acceptedBaitIds: ["worm", "sweet-corn", "crayfish"],
    preferredLureIds: [],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "smallmouth-bass",
    commonName: "Smallmouth Bass",
    scientificName: "Micropterus dolomieu",
    description: "A bronze, hard-fighting bass that favours clear water and rocky structure.",
    habitat: "Rocky shoals, gravel points, and cool clear water.",
    nativeRange: "Great Lakes and eastern North American freshwater systems.",
    minimumWeightKg: 0.15,
    typicalWeightKg: 0.9,
    maximumWeightKg: 4,
    minimumLengthCm: 18,
    typicalLengthCm: 35,
    maximumLengthCm: 55,
    rarity: "uncommon",
    baseValueCoins: 35,
    difficulty: 0.42,
    movementProfile: { speed: 0.56, acceleration: 0.62, directionChangeFrequency: 0.48, unpredictability: 0.34, fightDurationSeconds: 18 },
    acceptedBaitIds: ["worm", "minnow", "crayfish"],
    preferredLureIds: ["copper-spinner", "silver-spinner"],
    availableLocationIds: ["willow-pond", "pinewater-lake", "granite-reservoir", "silverpine-river"],
  }),
  fish({
    id: "largemouth-bass",
    commonName: "Largemouth Bass",
    scientificName: "Micropterus salmoides",
    description: "A green ambush predator that waits near weeds, timber, and warm cover.",
    habitat: "Warm shallows, weed beds, timber, and sheltered bays.",
    nativeRange: "Southern Ontario, the lower Great Lakes, and eastern North America.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 1.1,
    maximumWeightKg: 4.7,
    minimumLengthCm: 20,
    typicalLengthCm: 38,
    maximumLengthCm: 60,
    rarity: "uncommon",
    baseValueCoins: 42,
    difficulty: 0.46,
    movementProfile: { speed: 0.5, acceleration: 0.72, directionChangeFrequency: 0.38, unpredictability: 0.38, fightDurationSeconds: 20 },
    acceptedBaitIds: ["minnow", "crayfish"],
    preferredLureIds: ["silver-spinner"],
    availableLocationIds: ["pinewater-lake"],
  }),
  fish({
    id: "walleye",
    commonName: "Walleye",
    scientificName: "Sander vitreus",
    description: "A light-sensitive predator that often feeds near the bottom in deeper water.",
    habitat: "Deep edges, rocky shoals, and large cool lakes.",
    nativeRange: "Great Lakes, central Canada, and northern United States freshwater systems.",
    minimumWeightKg: 0.3,
    typicalWeightKg: 1.3,
    maximumWeightKg: 9,
    minimumLengthCm: 25,
    typicalLengthCm: 45,
    maximumLengthCm: 90,
    rarity: "rare",
    baseValueCoins: 90,
    difficulty: 0.6,
    movementProfile: { speed: 0.48, acceleration: 0.54, directionChangeFrequency: 0.58, unpredictability: 0.42, fightDurationSeconds: 23 },
    acceptedBaitIds: ["minnow", "crayfish", "premium-minnow"],
    preferredLureIds: ["silver-spinner", "deep-diver"],
    availableLocationIds: ["pinewater-lake", "granite-reservoir", "lake-greywater", "northwind-channel"],
  }),
  fish({
    id: "northern-pike",
    commonName: "Northern Pike",
    scientificName: "Esox lucius",
    description: "An aggressive freshwater predator that strikes near weeds and drop-offs.",
    habitat: "Shallow weeds, weedy edges, and deeper drop-offs.",
    nativeRange: "Freshwater systems across Ontario, the Great Lakes, and the northern hemisphere.",
    minimumWeightKg: 0.3,
    typicalWeightKg: 2.5,
    maximumWeightKg: 20,
    minimumLengthCm: 30,
    typicalLengthCm: 65,
    maximumLengthCm: 120,
    rarity: "rare",
    baseValueCoins: 120,
    difficulty: 0.72,
    movementProfile: { speed: 0.64, acceleration: 0.9, directionChangeFrequency: 0.46, unpredictability: 0.52, fightDurationSeconds: 27 },
    acceptedBaitIds: ["minnow", "premium-minnow"],
    preferredLureIds: ["silver-spinner", "deep-diver"],
    availableLocationIds: ["pinewater-lake", "granite-reservoir", "lake-greywater", "northwind-channel"],
  }),
  fish({
    id: "channel-catfish",
    commonName: "Channel Catfish",
    scientificName: "Ictalurus punctatus",
    description: "A whiskered bottom-feeder that becomes especially active in warm water.",
    habitat: "Deep holes, soft bottoms, and slow-moving freshwater.",
    nativeRange: "Central and eastern North America, including introduced Great Lakes waters.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 2,
    maximumWeightKg: 15,
    minimumLengthCm: 25,
    typicalLengthCm: 60,
    maximumLengthCm: 120,
    rarity: "uncommon",
    baseValueCoins: 55,
    difficulty: 0.52,
    movementProfile: { speed: 0.36, acceleration: 0.68, directionChangeFrequency: 0.22, unpredictability: 0.4, fightDurationSeconds: 25 },
    acceptedBaitIds: ["worm", "crayfish"],
    preferredLureIds: [],
    availableLocationIds: ["pinewater-lake"],
  }),
  fish({
    id: "lake-trout",
    commonName: "Lake Trout",
    scientificName: "Salvelinus namaycush",
    description: "A cold-water char that patrols deep, clear basins and steep contours.",
    habitat: "Deep, cold, well-oxygenated lake water.",
    nativeRange: "The Great Lakes and cold freshwater systems of northern North America.",
    minimumWeightKg: 0.5,
    typicalWeightKg: 3,
    maximumWeightKg: 15,
    minimumLengthCm: 35,
    typicalLengthCm: 60,
    maximumLengthCm: 100,
    rarity: "rare",
    baseValueCoins: 180,
    difficulty: 0.68,
    movementProfile: { speed: 0.52, acceleration: 0.5, directionChangeFrequency: 0.62, unpredictability: 0.46, fightDurationSeconds: 30 },
    acceptedBaitIds: ["minnow", "premium-minnow"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater", "northwind-channel", "superior-reach", "stormglass-basin"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
  fish({
    id: "chinook-salmon",
    commonName: "Chinook Salmon",
    scientificName: "Oncorhynchus tshawytscha",
    description: "A powerful Great Lakes sport fish known for long, forceful runs.",
    habitat: "Open cold water and tributary approaches during seasonal runs.",
    nativeRange: "Pacific origin; introduced populations now inhabit the Great Lakes.",
    minimumWeightKg: 1,
    typicalWeightKg: 5,
    maximumWeightKg: 25,
    minimumLengthCm: 45,
    typicalLengthCm: 80,
    maximumLengthCm: 120,
    rarity: "rare",
    baseValueCoins: 260,
    difficulty: 0.8,
    movementProfile: { speed: 0.72, acceleration: 0.82, directionChangeFrequency: 0.52, unpredictability: 0.58, fightDurationSeconds: 35 },
    acceptedBaitIds: ["premium-minnow", "lake-smelt", "spawn-sack"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater", "superior-reach", "stormglass-basin"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
  fish({
    id: "coho-salmon",
    commonName: "Coho Salmon",
    scientificName: "Oncorhynchus kisutch",
    description: "A fast, acrobatic salmon that turns a clean hookset into a lively fight.",
    habitat: "Cold open water and tributary approaches.",
    nativeRange: "Pacific origin; introduced populations now inhabit the Great Lakes.",
    minimumWeightKg: 0.8,
    typicalWeightKg: 3,
    maximumWeightKg: 12,
    minimumLengthCm: 40,
    typicalLengthCm: 65,
    maximumLengthCm: 100,
    rarity: "rare",
    baseValueCoins: 220,
    difficulty: 0.76,
    movementProfile: { speed: 0.78, acceleration: 0.74, directionChangeFrequency: 0.7, unpredictability: 0.54, fightDurationSeconds: 31 },
    acceptedBaitIds: ["premium-minnow"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater", "superior-reach"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
  fish({
    id: "muskellunge",
    commonName: "Muskellunge",
    scientificName: "Esox masquinongy",
    description: "A scarce apex predator whose size and power make every encounter consequential.",
    habitat: "Clear bays, weed edges, and large-lake structure.",
    nativeRange: "The Great Lakes basin and connected freshwater systems of eastern North America.",
    minimumWeightKg: 2,
    typicalWeightKg: 8,
    maximumWeightKg: 30,
    minimumLengthCm: 60,
    typicalLengthCm: 100,
    maximumLengthCm: 150,
    rarity: "legendary",
    baseValueCoins: 600,
    difficulty: 0.94,
    movementProfile: { speed: 0.86, acceleration: 0.96, directionChangeFrequency: 0.8, unpredictability: 0.72, fightDurationSeconds: 45 },
    acceptedBaitIds: ["premium-minnow"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater", "superior-reach", "stormglass-basin"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
  progressionFish({
    id: "creek-chub", commonName: "Creek Chub", scientificName: "Semotilus atromaculatus",
    description: "A bold little stream fish that gathers below riffles and shaded banks.",
    habitat: "Small streams, creek pools, and gravel runs.", nativeRange: "Fresh waters across Ontario and eastern North America.",
    minimumWeightKg: 0.02, typicalWeightKg: 0.12, maximumWeightKg: 0.5,
    minimumLengthCm: 6, typicalLengthCm: 18, maximumLengthCm: 32,
    rarity: "common", baseValueCoins: 8, difficulty: 0.1, fightDurationSeconds: 8,
    acceptedBaitIds: ["sweet-corn"], preferredLureIds: ["micro-spoon"], availableLocationIds: ["mill-creek"],
  }),
  progressionFish({
    id: "golden-shiner", commonName: "Golden Shiner", scientificName: "Notemigonus crysoleucas",
    description: "A flashing, deep-bodied minnow that schools around warm vegetation.",
    habitat: "Weedy ponds, slow rivers, and quiet lake margins.", nativeRange: "Fresh waters of eastern North America, including southern Ontario.",
    minimumWeightKg: 0.02, typicalWeightKg: 0.14, maximumWeightKg: 0.8,
    minimumLengthCm: 7, typicalLengthCm: 20, maximumLengthCm: 36,
    rarity: "uncommon", baseValueCoins: 18, difficulty: 0.2, fightDurationSeconds: 10,
    acceptedBaitIds: ["worm", "sweet-corn"], preferredLureIds: ["micro-spoon"], availableLocationIds: ["willow-pond"],
  }),
  progressionFish({
    id: "yellow-bullhead", commonName: "Yellow Bullhead", scientificName: "Ameiurus natalis",
    description: "A compact nocturnal catfish with a stubborn pull and a taste for natural bait.",
    habitat: "Warm ponds, slow creeks, and soft-bottomed shallows.", nativeRange: "Southern Ontario and freshwater systems of eastern North America.",
    minimumWeightKg: 0.06, typicalWeightKg: 0.35, maximumWeightKg: 1.8,
    minimumLengthCm: 12, typicalLengthCm: 28, maximumLengthCm: 48,
    rarity: "uncommon", baseValueCoins: 26, difficulty: 0.27, fightDurationSeconds: 13,
    acceptedBaitIds: ["worm", "nightcrawler"], preferredLureIds: [], availableLocationIds: ["mill-creek"],
  }),
  progressionFish({
    id: "white-sucker", commonName: "White Sucker", scientificName: "Catostomus commersonii",
    description: "A strong river bottom-feeder that turns inexpensive bait into a steady payday.",
    habitat: "Creeks, rivers, and shallow lake bottoms.", nativeRange: "Widespread across Ontario and northern North America.",
    minimumWeightKg: 0.08, typicalWeightKg: 0.7, maximumWeightKg: 3.2,
    minimumLengthCm: 15, typicalLengthCm: 38, maximumLengthCm: 65,
    rarity: "common", baseValueCoins: 22, difficulty: 0.3, fightDurationSeconds: 15,
    acceptedBaitIds: ["nightcrawler", "leech", "dough-ball"], preferredLureIds: [], availableLocationIds: ["mill-creek", "pinewater-lake"],
  }),
  progressionFish({
    id: "brown-bullhead", commonName: "Brown Bullhead", scientificName: "Ameiurus nebulosus",
    description: "A hardy whiskered fish that feeds after dark along muddy creek bottoms.",
    habitat: "Warm ponds, marsh channels, and slow soft-bottomed water.", nativeRange: "Great Lakes basin and eastern North America.",
    minimumWeightKg: 0.05, typicalWeightKg: 0.45, maximumWeightKg: 2.5,
    minimumLengthCm: 12, typicalLengthCm: 30, maximumLengthCm: 55,
    rarity: "common", baseValueCoins: 20, difficulty: 0.28, fightDurationSeconds: 14,
    acceptedBaitIds: ["nightcrawler", "dough-ball"], preferredLureIds: [], availableLocationIds: ["mill-creek"],
  }),
  progressionFish({
    id: "brook-trout", commonName: "Brook Trout", scientificName: "Salvelinus fontinalis",
    description: "A jewel-coloured native char that rewards precise casts into cold, shaded water.",
    habitat: "Cool spring-fed streams and clear northern lakes.", nativeRange: "Native across much of Ontario and eastern North America.",
    minimumWeightKg: 0.08, typicalWeightKg: 0.7, maximumWeightKg: 6.6,
    minimumLengthCm: 15, typicalLengthCm: 35, maximumLengthCm: 75,
    rarity: "rare", baseValueCoins: 60, difficulty: 0.48, fightDurationSeconds: 20,
    acceptedBaitIds: ["minnow", "leech", "salmon-egg"], preferredLureIds: ["micro-spoon", "river-fly"], availableLocationIds: ["mill-creek", "granite-reservoir", "silverpine-river"],
  }),
  progressionFish({
    id: "white-crappie", commonName: "White Crappie", scientificName: "Pomoxis annularis",
    description: "A pale, barred crappie that suspends beside timber and open reed edges.",
    habitat: "Warm quiet bays, flooded wood, and turbid shallows.", nativeRange: "Central North America with established populations around the lower Great Lakes.",
    minimumWeightKg: 0.04, typicalWeightKg: 0.28, maximumWeightKg: 2.1,
    minimumLengthCm: 9, typicalLengthCm: 24, maximumLengthCm: 52,
    rarity: "uncommon", baseValueCoins: 30, difficulty: 0.3, fightDurationSeconds: 13,
    acceptedBaitIds: ["sweet-corn", "minnow"], preferredLureIds: ["marsh-jig", "micro-spoon"], availableLocationIds: ["cedar-marsh"],
  }),
  progressionFish({
    id: "longnose-gar", commonName: "Longnose Gar", scientificName: "Lepisosteus osseus",
    description: "An armoured ambush hunter whose sudden sideways runs punish light tackle.",
    habitat: "Warm shallows, marsh mouths, and slow vegetated water.", nativeRange: "Great Lakes basin and eastern North American waterways.",
    minimumWeightKg: 0.5, typicalWeightKg: 3.5, maximumWeightKg: 18,
    minimumLengthCm: 45, typicalLengthCm: 90, maximumLengthCm: 150,
    rarity: "rare", baseValueCoins: 135, difficulty: 0.7, fightDurationSeconds: 29,
    acceptedBaitIds: ["crayfish", "cut-bait"], preferredLureIds: ["topwater-frog", "giant-bucktail"], availableLocationIds: ["cedar-marsh"],
  }),
  progressionFish({
    id: "shorthead-redhorse", commonName: "Shorthead Redhorse", scientificName: "Moxostoma macrolepidotum",
    description: "A copper-finned sucker that digs into current and fights far above its reputation.",
    habitat: "Clean rivers, gravel runs, and lake shallows.", nativeRange: "Great Lakes and Mississippi drainage systems.",
    minimumWeightKg: 0.12, typicalWeightKg: 1.1, maximumWeightKg: 4.5,
    minimumLengthCm: 20, typicalLengthCm: 45, maximumLengthCm: 75,
    rarity: "uncommon", baseValueCoins: 48, difficulty: 0.4, fightDurationSeconds: 19,
    acceptedBaitIds: ["sweet-corn", "nightcrawler", "dough-ball"], preferredLureIds: ["tube-jig"], availableLocationIds: ["cedar-marsh"],
  }),
  progressionFish({
    id: "sauger", commonName: "Sauger", scientificName: "Sander canadensis",
    description: "A mottled walleye relative that hunts close to bottom in turbid current.",
    habitat: "Large rivers, cloudy reservoirs, and deep current seams.", nativeRange: "Central Canadian and northern United States watersheds.",
    minimumWeightKg: 0.15, typicalWeightKg: 0.8, maximumWeightKg: 4,
    minimumLengthCm: 20, typicalLengthCm: 38, maximumLengthCm: 70,
    rarity: "uncommon", baseValueCoins: 58, difficulty: 0.5, fightDurationSeconds: 21,
    acceptedBaitIds: ["minnow", "leech", "premium-minnow"], preferredLureIds: ["silver-spinner", "tube-jig"], availableLocationIds: ["pinewater-lake", "silverpine-river"],
  }),
  progressionFish({
    id: "splake", commonName: "Splake", scientificName: "Salvelinus fontinalis × namaycush",
    description: "A stocked brook-trout and lake-trout hybrid with cold-water speed and solid weight.",
    habitat: "Deep, cool inland lakes and rocky reservoir basins.", nativeRange: "Stocked in selected Ontario cold-water lakes.",
    minimumWeightKg: 0.2, typicalWeightKg: 1.4, maximumWeightKg: 9,
    minimumLengthCm: 25, typicalLengthCm: 48, maximumLengthCm: 90,
    rarity: "rare", baseValueCoins: 125, difficulty: 0.62, fightDurationSeconds: 25,
    acceptedBaitIds: ["minnow", "leech", "premium-minnow"], preferredLureIds: ["deep-diver", "trolling-spoon"], availableLocationIds: ["granite-reservoir"],
  }),
  progressionFish({
    id: "burbot", commonName: "Burbot", scientificName: "Lota lota",
    description: "A powerful cold-water cod that twists and dives in the deepest basins.",
    habitat: "Deep cold lakes and large rivers, especially over rock and sand.", nativeRange: "Cold fresh waters across Ontario and the northern hemisphere.",
    minimumWeightKg: 0.2, typicalWeightKg: 2, maximumWeightKg: 11,
    minimumLengthCm: 25, typicalLengthCm: 60, maximumLengthCm: 110,
    rarity: "uncommon", baseValueCoins: 105, difficulty: 0.58, fightDurationSeconds: 25,
    acceptedBaitIds: ["leech", "cut-bait", "lake-smelt"], preferredLureIds: ["deep-diver", "tube-jig"], availableLocationIds: ["granite-reservoir", "lake-greywater", "northwind-channel", "superior-reach", "stormglass-basin"],
  }),
  progressionFish({
    id: "lake-whitefish", commonName: "Lake Whitefish", scientificName: "Coregonus clupeaformis",
    description: "A silvery cold-water fish prized for its subtle bite and steady deep pull.",
    habitat: "Cold lake bottoms, offshore shoals, and deep basins.", nativeRange: "Great Lakes and cold inland lakes across Canada.",
    minimumWeightKg: 0.25, typicalWeightKg: 1.8, maximumWeightKg: 9,
    minimumLengthCm: 25, typicalLengthCm: 52, maximumLengthCm: 90,
    rarity: "uncommon", baseValueCoins: 115, difficulty: 0.55, fightDurationSeconds: 24,
    acceptedBaitIds: ["minnow", "premium-minnow"], preferredLureIds: ["micro-spoon", "deep-diver"], availableLocationIds: ["granite-reservoir", "lake-greywater", "superior-reach"],
  }),
  progressionFish({
    id: "rainbow-trout", commonName: "Rainbow Trout", scientificName: "Oncorhynchus mykiss",
    description: "A bright, acrobatic trout that leaps, changes direction, and uses current expertly.",
    habitat: "Cold rivers, tributary mouths, and Great Lakes nearshore water.", nativeRange: "Introduced and naturalized throughout the Great Lakes watershed.",
    minimumWeightKg: 0.2, typicalWeightKg: 2.3, maximumWeightKg: 18.5,
    minimumLengthCm: 25, typicalLengthCm: 55, maximumLengthCm: 110,
    rarity: "rare", baseValueCoins: 185, difficulty: 0.72, fightDurationSeconds: 29,
    acceptedBaitIds: ["minnow", "leech", "salmon-egg", "spawn-sack"], preferredLureIds: ["river-fly", "trolling-spoon"], availableLocationIds: ["silverpine-river", "northwind-channel"],
  }),
  progressionFish({
    id: "brown-trout", commonName: "Brown Trout", scientificName: "Salmo trutta",
    description: "A wary, powerful trout that hugs structure before making a heavy downstream run.",
    habitat: "Cold rivers, deep pools, tributaries, and Great Lakes shorelines.", nativeRange: "Introduced from Europe and established in Ontario waters.",
    minimumWeightKg: 0.2, typicalWeightKg: 1.8, maximumWeightKg: 18,
    minimumLengthCm: 25, typicalLengthCm: 50, maximumLengthCm: 105,
    rarity: "rare", baseValueCoins: 170, difficulty: 0.7, fightDurationSeconds: 28,
    acceptedBaitIds: ["minnow", "leech", "salmon-egg", "spawn-sack"], preferredLureIds: ["river-fly", "trolling-spoon"], availableLocationIds: ["silverpine-river", "northwind-channel"],
  }),
  progressionFish({
    id: "mooneye", commonName: "Mooneye", scientificName: "Hiodon tergisus",
    description: "A silver river fish with a large eye and a surprisingly quick surface fight.",
    habitat: "Large clear rivers, current edges, and connected lake channels.", nativeRange: "Great Lakes, Hudson Bay, and Mississippi drainage systems.",
    minimumWeightKg: 0.08, typicalWeightKg: 0.45, maximumWeightKg: 1.8,
    minimumLengthCm: 15, typicalLengthCm: 32, maximumLengthCm: 50,
    rarity: "uncommon", baseValueCoins: 62, difficulty: 0.48, fightDurationSeconds: 19,
    acceptedBaitIds: ["minnow", "nightcrawler"], preferredLureIds: ["micro-spoon", "river-fly"], availableLocationIds: ["silverpine-river"],
  }),
  progressionFish({
    id: "cisco", commonName: "Cisco", scientificName: "Coregonus artedi",
    description: "A delicate open-water schooling fish that supports the lake's largest predators.",
    habitat: "Cool open water and deep offshore schools.", nativeRange: "Great Lakes and cold lakes across northern North America.",
    minimumWeightKg: 0.05, typicalWeightKg: 0.45, maximumWeightKg: 1.8,
    minimumLengthCm: 12, typicalLengthCm: 32, maximumLengthCm: 55,
    rarity: "uncommon", baseValueCoins: 78, difficulty: 0.44, fightDurationSeconds: 18,
    acceptedBaitIds: ["premium-minnow"], preferredLureIds: ["micro-spoon", "deep-diver"], availableLocationIds: ["lake-greywater"], source: LAKE_ONTARIO_OBJECTIVES,
  }),
  progressionFish({
    id: "rainbow-smelt", commonName: "Rainbow Smelt", scientificName: "Osmerus mordax",
    description: "A slim cold-water forage fish whose huge schools draw predators from the depths.",
    habitat: "Cool nearshore water and deep open-lake schools.", nativeRange: "Atlantic drainage origin with established Great Lakes populations.",
    minimumWeightKg: 0.01, typicalWeightKg: 0.05, maximumWeightKg: 0.25,
    minimumLengthCm: 6, typicalLengthCm: 18, maximumLengthCm: 30,
    rarity: "common", baseValueCoins: 54, difficulty: 0.34, fightDurationSeconds: 14,
    acceptedBaitIds: ["minnow"], preferredLureIds: ["micro-spoon"], availableLocationIds: ["lake-greywater"], source: LAKE_ONTARIO_OBJECTIVES,
  }),
  progressionFish({
    id: "atlantic-salmon", commonName: "Atlantic Salmon", scientificName: "Salmo salar",
    description: "A scarce restoration-era salmon with speed, stamina, and enormous discovery value.",
    habitat: "Cold Great Lakes water and connected spawning rivers.", nativeRange: "Historically native to Lake Ontario; supported today through restoration.",
    minimumWeightKg: 0.7, typicalWeightKg: 4, maximumWeightKg: 18,
    minimumLengthCm: 40, typicalLengthCm: 75, maximumLengthCm: 115,
    rarity: "legendary", baseValueCoins: 520, difficulty: 0.88, fightDurationSeconds: 38,
    acceptedBaitIds: ["premium-minnow", "leech", "salmon-egg", "lake-smelt", "spawn-sack"], preferredLureIds: ["river-fly", "salmon-flasher"], availableLocationIds: ["northwind-channel", "superior-reach"], source: LAKE_ONTARIO_OBJECTIVES,
  }),
  progressionFish({
    id: "pink-salmon", commonName: "Pink Salmon", scientificName: "Oncorhynchus gorbuscha",
    description: "A compact migratory salmon that arrives in bursts and fights with sharp direction changes.",
    habitat: "Cold open water, river mouths, and spawning tributaries.", nativeRange: "Pacific origin with self-sustaining Great Lakes populations.",
    minimumWeightKg: 0.35, typicalWeightKg: 1.5, maximumWeightKg: 6.5,
    minimumLengthCm: 30, typicalLengthCm: 52, maximumLengthCm: 78,
    rarity: "rare", baseValueCoins: 245, difficulty: 0.74, fightDurationSeconds: 30,
    acceptedBaitIds: ["premium-minnow", "salmon-egg", "lake-smelt", "spawn-sack"], preferredLureIds: ["trolling-spoon", "salmon-flasher"], availableLocationIds: ["northwind-channel", "superior-reach"],
  }),
  progressionFish({
    id: "american-eel", commonName: "American Eel", scientificName: "Anguilla rostrata",
    description: "A rare, serpentine migrant that coils, dives, and refuses to come quietly.",
    habitat: "Deep channels, river mouths, and connected Great Lakes waters.", nativeRange: "Atlantic drainage and Lake Ontario watershed.",
    minimumWeightKg: 0.15, typicalWeightKg: 1.2, maximumWeightKg: 7.5,
    minimumLengthCm: 30, typicalLengthCm: 70, maximumLengthCm: 125,
    rarity: "legendary", baseValueCoins: 430, difficulty: 0.82, fightDurationSeconds: 34,
    acceptedBaitIds: ["nightcrawler", "cut-bait"], preferredLureIds: ["tube-jig"], availableLocationIds: ["northwind-channel", "stormglass-basin"],
  }),
  progressionFish({
    id: "lake-sturgeon", commonName: "Lake Sturgeon", scientificName: "Acipenser fulvescens",
    description: "An ancient armoured giant whose slow first pull can become an unstoppable run.",
    habitat: "Large lakes and rivers over sand, gravel, and deep channels.", nativeRange: "Great Lakes, Hudson Bay, and Mississippi drainage systems.",
    minimumWeightKg: 2, typicalWeightKg: 18, maximumWeightKg: 90,
    minimumLengthCm: 55, typicalLengthCm: 125, maximumLengthCm: 220,
    rarity: "legendary", baseValueCoins: 950, difficulty: 0.97, fightDurationSeconds: 48,
    acceptedBaitIds: ["cut-bait", "spawn-sack"], preferredLureIds: ["giant-bucktail"], availableLocationIds: ["superior-reach", "stormglass-basin"],
  }),
  progressionFish({
    id: "quillback", commonName: "Quillback", scientificName: "Carpiodes cyprinus",
    description: "A deep-bodied river fish with a tall first dorsal ray and relentless weight on the line.",
    habitat: "Large rivers, deep channels, and quiet lake backwaters.", nativeRange: "Great Lakes, Hudson Bay, and Mississippi drainage systems.",
    minimumWeightKg: 0.2, typicalWeightKg: 1.8, maximumWeightKg: 8,
    minimumLengthCm: 22, typicalLengthCm: 48, maximumLengthCm: 80,
    rarity: "rare", baseValueCoins: 210, difficulty: 0.62, fightDurationSeconds: 27,
    acceptedBaitIds: ["nightcrawler", "dough-ball"], preferredLureIds: ["tube-jig"], availableLocationIds: ["stormglass-basin"],
  }),
];

export const GAME_CATALOG: GameCatalog = {
  locations,
  boats,
  rods,
  lures: [...lures].sort((left, right) => left.priceCoins - right.priceCoins),
  baits: [...baits].sort((left, right) => left.priceCoins - right.priceCoins),
  fish: fishSpecies,
};
