import type {
  BaitDefinition,
  BoatDefinition,
  FishSpecies,
  GameCatalog,
  LocationDefinition,
  LureDefinition,
  RodDefinition,
} from "./contracts";

const ONTARIO_FISH_GUIDE = {
  name: "Ontario Learn to Fish guide",
  url: "https://www.ontario.ca/page/learn-fish-guide",
};

const LAKE_ONTARIO_OBJECTIVES = {
  name: "Fish Community Objectives for Lake Ontario",
  url: "https://files.ontario.ca/mnrf-fish-community-objectives-lake-ontario-en-2019-10-02.pdf",
};

const locations: LocationDefinition[] = [
  {
    id: "willow-pond",
    name: "Willow Pond",
    description: "A calm, weedy starter pond where light tackle and patient hands are enough.",
    riskReason: "Shallow water and smaller fish keep strain on a suitable rod low.",
    riskBand: "low",
    requiredBoatId: "shore-fishing",
    expectedValueMinCoins: 8,
    expectedValueMaxCoins: 75,
    fishIds: ["yellow-perch", "pumpkinseed", "rock-bass", "bluegill", "smallmouth-bass"],
  },
  {
    id: "cedar-marsh",
    name: "Cedar Marsh",
    description: "A maze of lily pads and flooded timber where patient casts uncover ambush predators.",
    riskReason: "Flooded timber and strong bottom-feeders can load a light rod quickly.",
    riskBand: "moderate",
    requiredBoatId: "rowboat",
    expectedValueMinCoins: 12,
    expectedValueMaxCoins: 750,
    fishIds: ["black-crappie", "common-carp", "bowfin", "freshwater-drum"],
  },
  {
    id: "pinewater-lake",
    name: "Pinewater Lake",
    description: "Cooler water and deeper structure bring stronger fish and better opportunities.",
    riskReason: "Deeper water creates longer fights, and the larger fish can exceed starter tackle.",
    riskBand: "moderate",
    requiredBoatId: "rowboat",
    expectedValueMinCoins: 28,
    expectedValueMaxCoins: 300,
    fishIds: ["smallmouth-bass", "largemouth-bass", "walleye", "northern-pike", "channel-catfish"],
  },
  {
    id: "lake-greywater",
    name: "Lake Greywater",
    description: "A deep Great Lakes-inspired water where serious tackle meets trophy fish.",
    riskReason: "Trophy fish and open-water runs can overload a rod before you land them.",
    riskBand: "high",
    requiredBoatId: "fishing-skiff",
    expectedValueMinCoins: 100,
    expectedValueMaxCoins: 2400,
    fishIds: ["lake-trout", "chinook-salmon", "coho-salmon", "walleye", "northern-pike", "muskellunge"],
  },
];

const boats: BoatDefinition[] = [
  {
    id: "shore-fishing",
    name: "Shore Fishing",
    description: "A sturdy bank-side setup for Willow Pond.",
    tier: 1,
    priceCoins: 0,
    unlocksLocationIds: ["willow-pond"],
  },
  {
    id: "rowboat",
    name: "Rowboat",
    description: "Reach the reed beds of Cedar Marsh and the quiet coves of Pinewater Lake.",
    tier: 2,
    priceCoins: 450,
    unlocksLocationIds: ["willow-pond", "cedar-marsh", "pinewater-lake"],
  },
  {
    id: "fishing-skiff",
    name: "Fishing Skiff",
    description: "A stable platform for the deep water of Lake Greywater.",
    tier: 3,
    priceCoins: 2200,
    unlocksLocationIds: ["willow-pond", "pinewater-lake", "lake-greywater"],
  },
];

const rods: RodDefinition[] = [
  {
    id: "starter-fiberglass",
    name: "Starter Fiberglass",
    description: "Forgiving and reliable for small pond fish.",
    priceCoins: 0,
    strength: 1,
    control: 1,
    maxFishWeightKg: 2.5,
    breakResistance: 0.995,
    catchZoneBonus: 0.02,
  },
  {
    id: "medium-heavy-carbon",
    name: "Medium-Heavy Carbon",
    description: "A responsive rod for bass, walleye, and pike.",
    priceCoins: 650,
    strength: 2,
    control: 1.18,
    maxFishWeightKg: 8,
    breakResistance: 0.99,
    catchZoneBonus: 0.06,
  },
  {
    id: "lake-heavy",
    name: "Lake Heavy",
    description: "Built for powerful fish and long fights in open water.",
    priceCoins: 2400,
    strength: 3,
    control: 1.32,
    maxFishWeightKg: 18,
    breakResistance: 0.985,
    catchZoneBonus: 0.1,
  },
];

const lures: LureDefinition[] = [
  {
    id: "copper-spinner",
    name: "Copper Spinner",
    description: "A dependable all-purpose lure for shallow water.",
    priceCoins: 40,
    maximumDurability: 10,
    catchZoneBonus: 0.02,
    difficultyModifier: 0,
    preferredFishIds: ["yellow-perch", "pumpkinseed", "rock-bass", "bluegill", "smallmouth-bass"],
  },
  {
    id: "silver-spinner",
    name: "Silver Spinner",
    description: "A bright spinner that draws active predators.",
    priceCoins: 120,
    maximumDurability: 12,
    catchZoneBonus: 0.04,
    difficultyModifier: 0.03,
    preferredFishIds: ["smallmouth-bass", "largemouth-bass", "walleye", "northern-pike"],
  },
  {
    id: "marsh-jig",
    name: "Marsh Jig",
    description: "A compact jig that slips through reeds and lily pads without spooking cover fish.",
    priceCoins: 70,
    maximumDurability: 11,
    catchZoneBonus: 0.03,
    difficultyModifier: 0.015,
    preferredFishIds: ["black-crappie", "bowfin", "yellow-perch"],
  },
  {
    id: "deep-diver",
    name: "Deep Diver",
    description: "A hard-running lure for cold, deep-water fish.",
    priceCoins: 300,
    maximumDurability: 15,
    catchZoneBonus: 0.06,
    difficultyModifier: 0.06,
    preferredFishIds: ["lake-trout", "chinook-salmon", "coho-salmon", "muskellunge"],
  },
];

const baits: BaitDefinition[] = [
  {
    id: "worm",
    name: "Worm",
    description: "A simple, reliable bait that keeps a new angler fishing.",
    priceCoins: 8,
    attraction: 1,
    fishIds: ["yellow-perch", "pumpkinseed", "rock-bass", "bluegill", "smallmouth-bass", "channel-catfish"],
  },
  {
    id: "sweet-corn",
    name: "Sweet Corn",
    description: "A bright, patient bait for marsh panfish and hungry bottom-feeders.",
    priceCoins: 12,
    attraction: 1.08,
    fishIds: ["black-crappie", "common-carp", "freshwater-drum"],
  },
  {
    id: "minnow",
    name: "Minnow",
    description: "Live bait that attracts bass, walleye, and pike.",
    priceCoins: 20,
    attraction: 1.2,
    fishIds: ["smallmouth-bass", "largemouth-bass", "walleye", "northern-pike", "lake-trout"],
  },
  {
    id: "crayfish",
    name: "Crayfish",
    description: "A meaty bait for hard-fighting bass and catfish.",
    priceCoins: 28,
    attraction: 1.24,
    fishIds: ["smallmouth-bass", "largemouth-bass", "channel-catfish", "walleye"],
  },
  {
    id: "premium-minnow",
    name: "Premium Minnow",
    description: "A carefully selected minnow for cold-water predators.",
    priceCoins: 55,
    attraction: 1.5,
    fishIds: ["walleye", "northern-pike", "lake-trout", "chinook-salmon", "coho-salmon", "muskellunge"],
  },
];

function fish(input: Omit<FishSpecies, "source"> & { source?: FishSpecies["source"] }): FishSpecies {
  return { ...input, source: input.source ?? ONTARIO_FISH_GUIDE };
}

const fishSpecies: FishSpecies[] = [
  fish({
    id: "yellow-perch",
    commonName: "Yellow Perch",
    scientificName: "Perca flavescens",
    description: "A schooling freshwater fish often found around weeds and gentle structure.",
    habitat: "Shallow weeds, sandy shoals, and quiet lake edges.",
    nativeRange: "Freshwater systems across the Great Lakes and much of eastern North America.",
    minimumWeightKg: 0.05,
    typicalWeightKg: 0.25,
    maximumWeightKg: 1.9,
    minimumLengthCm: 10,
    typicalLengthCm: 25,
    maximumLengthCm: 50,
    rarity: "common",
    baseValueCoins: 12,
    difficulty: 0.16,
    movementProfile: { speed: 0.28, acceleration: 0.18, directionChangeFrequency: 0.24, unpredictability: 0.12, fightDurationSeconds: 10 },
    acceptedBaitIds: ["worm", "minnow"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond"],
  }),
  fish({
    id: "pumpkinseed",
    commonName: "Pumpkinseed",
    scientificName: "Lepomis gibbosus",
    description: "A brightly marked sunfish that prefers cover, plants, and calm water.",
    habitat: "Vegetated ponds, quiet bays, and protected lake margins.",
    nativeRange: "Freshwater systems of eastern North America, including the Great Lakes.",
    minimumWeightKg: 0.04,
    typicalWeightKg: 0.18,
    maximumWeightKg: 0.8,
    minimumLengthCm: 8,
    typicalLengthCm: 18,
    maximumLengthCm: 30,
    rarity: "common",
    baseValueCoins: 10,
    difficulty: 0.12,
    movementProfile: { speed: 0.24, acceleration: 0.16, directionChangeFrequency: 0.3, unpredictability: 0.14, fightDurationSeconds: 9 },
    acceptedBaitIds: ["worm"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond"],
  }),
  fish({
    id: "rock-bass",
    commonName: "Rock Bass",
    scientificName: "Ambloplites rupestris",
    description: "A stocky bass that holds close to rocks, logs, and shaded cover.",
    habitat: "Rocky shorelines, submerged timber, and clear quiet water.",
    nativeRange: "Eastern and central North American freshwater systems.",
    minimumWeightKg: 0.06,
    typicalWeightKg: 0.22,
    maximumWeightKg: 0.9,
    minimumLengthCm: 10,
    typicalLengthCm: 20,
    maximumLengthCm: 35,
    rarity: "common",
    baseValueCoins: 16,
    difficulty: 0.2,
    movementProfile: { speed: 0.32, acceleration: 0.25, directionChangeFrequency: 0.26, unpredictability: 0.18, fightDurationSeconds: 11 },
    acceptedBaitIds: ["worm", "crayfish"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond"],
  }),
  fish({
    id: "bluegill",
    commonName: "Bluegill",
    scientificName: "Lepomis macrochirus",
    description: "A common sunfish that feeds around vegetation and shallow cover.",
    habitat: "Warm, weedy shallows and protected freshwater coves.",
    nativeRange: "Central and eastern North American freshwater systems.",
    minimumWeightKg: 0.04,
    typicalWeightKg: 0.2,
    maximumWeightKg: 0.9,
    minimumLengthCm: 8,
    typicalLengthCm: 18,
    maximumLengthCm: 30,
    rarity: "common",
    baseValueCoins: 11,
    difficulty: 0.14,
    movementProfile: { speed: 0.26, acceleration: 0.19, directionChangeFrequency: 0.28, unpredictability: 0.15, fightDurationSeconds: 9 },
    acceptedBaitIds: ["worm"],
    preferredLureIds: ["copper-spinner"],
    availableLocationIds: ["willow-pond"],
  }),
  fish({
    id: "black-crappie",
    commonName: "Black Crappie",
    scientificName: "Pomoxis nigromaculatus",
    description: "A speckled panfish that gathers beneath shade, reeds, and submerged branches.",
    habitat: "Clear, quiet bays, weed lines, and brushy cover.",
    nativeRange: "Great Lakes and freshwater systems across central and eastern North America.",
    minimumWeightKg: 0.04,
    typicalWeightKg: 0.25,
    maximumWeightKg: 1.9,
    minimumLengthCm: 8,
    typicalLengthCm: 22,
    maximumLengthCm: 50,
    rarity: "common",
    baseValueCoins: 24,
    difficulty: 0.25,
    movementProfile: { speed: 0.3, acceleration: 0.24, directionChangeFrequency: 0.4, unpredictability: 0.2, fightDurationSeconds: 12 },
    acceptedBaitIds: ["worm", "sweet-corn", "minnow"],
    preferredLureIds: ["copper-spinner", "marsh-jig"],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "common-carp",
    commonName: "Common Carp",
    scientificName: "Cyprinus carpio",
    description: "A wary, broad-shouldered bottom-feeder that makes shallow marsh water feel much deeper.",
    habitat: "Muddy flats, warm bays, and slow water around soft-bottom structure.",
    nativeRange: "Introduced throughout Ontario and established in Great Lakes waters.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 4,
    maximumWeightKg: 20,
    minimumLengthCm: 25,
    typicalLengthCm: 65,
    maximumLengthCm: 120,
    rarity: "uncommon",
    baseValueCoins: 95,
    difficulty: 0.58,
    movementProfile: { speed: 0.42, acceleration: 0.78, directionChangeFrequency: 0.35, unpredictability: 0.45, fightDurationSeconds: 30 },
    acceptedBaitIds: ["worm", "sweet-corn"],
    preferredLureIds: [],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "bowfin",
    commonName: "Bowfin",
    scientificName: "Amia calva",
    description: "An ancient ambush predator that surges from heavy cover with surprising power.",
    habitat: "Warm, weedy backwaters, marsh channels, and flooded timber.",
    nativeRange: "Great Lakes basin and freshwater systems of eastern and central North America.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 1.3,
    maximumWeightKg: 5.5,
    minimumLengthCm: 25,
    typicalLengthCm: 55,
    maximumLengthCm: 90,
    rarity: "uncommon",
    baseValueCoins: 90,
    difficulty: 0.68,
    movementProfile: { speed: 0.62, acceleration: 0.78, directionChangeFrequency: 0.5, unpredictability: 0.48, fightDurationSeconds: 26 },
    acceptedBaitIds: ["minnow", "crayfish"],
    preferredLureIds: ["marsh-jig", "silver-spinner"],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "freshwater-drum",
    commonName: "Freshwater Drum",
    scientificName: "Aplodinotus grunniens",
    description: "A patient bottom-feeder with a deep-bodied pull and a distinctive drumming call.",
    habitat: "Rocky shoals, sandy flats, and deep channels with moving water.",
    nativeRange: "Great Lakes and freshwater systems across central and eastern North America.",
    minimumWeightKg: 0.15,
    typicalWeightKg: 2.5,
    maximumWeightKg: 12,
    minimumLengthCm: 20,
    typicalLengthCm: 55,
    maximumLengthCm: 100,
    rarity: "uncommon",
    baseValueCoins: 70,
    difficulty: 0.5,
    movementProfile: { speed: 0.38, acceleration: 0.64, directionChangeFrequency: 0.28, unpredictability: 0.35, fightDurationSeconds: 24 },
    acceptedBaitIds: ["worm", "sweet-corn", "crayfish"],
    preferredLureIds: [],
    availableLocationIds: ["cedar-marsh"],
  }),
  fish({
    id: "smallmouth-bass",
    commonName: "Smallmouth Bass",
    scientificName: "Micropterus dolomieu",
    description: "A bronze, hard-fighting bass that favours clear water and rocky structure.",
    habitat: "Rocky shoals, gravel points, and cool clear water.",
    nativeRange: "Great Lakes and eastern North American freshwater systems.",
    minimumWeightKg: 0.15,
    typicalWeightKg: 0.9,
    maximumWeightKg: 4,
    minimumLengthCm: 18,
    typicalLengthCm: 35,
    maximumLengthCm: 55,
    rarity: "uncommon",
    baseValueCoins: 35,
    difficulty: 0.42,
    movementProfile: { speed: 0.56, acceleration: 0.62, directionChangeFrequency: 0.48, unpredictability: 0.34, fightDurationSeconds: 18 },
    acceptedBaitIds: ["worm", "minnow", "crayfish"],
    preferredLureIds: ["copper-spinner", "silver-spinner"],
    availableLocationIds: ["willow-pond", "pinewater-lake"],
  }),
  fish({
    id: "largemouth-bass",
    commonName: "Largemouth Bass",
    scientificName: "Micropterus salmoides",
    description: "A green ambush predator that waits near weeds, timber, and warm cover.",
    habitat: "Warm shallows, weed beds, timber, and sheltered bays.",
    nativeRange: "Southern Ontario, the lower Great Lakes, and eastern North America.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 1.1,
    maximumWeightKg: 4.7,
    minimumLengthCm: 20,
    typicalLengthCm: 38,
    maximumLengthCm: 60,
    rarity: "uncommon",
    baseValueCoins: 42,
    difficulty: 0.46,
    movementProfile: { speed: 0.5, acceleration: 0.72, directionChangeFrequency: 0.38, unpredictability: 0.38, fightDurationSeconds: 20 },
    acceptedBaitIds: ["minnow", "crayfish"],
    preferredLureIds: ["silver-spinner"],
    availableLocationIds: ["pinewater-lake"],
  }),
  fish({
    id: "walleye",
    commonName: "Walleye",
    scientificName: "Sander vitreus",
    description: "A light-sensitive predator that often feeds near the bottom in deeper water.",
    habitat: "Deep edges, rocky shoals, and large cool lakes.",
    nativeRange: "Great Lakes, central Canada, and northern United States freshwater systems.",
    minimumWeightKg: 0.3,
    typicalWeightKg: 1.3,
    maximumWeightKg: 9,
    minimumLengthCm: 25,
    typicalLengthCm: 45,
    maximumLengthCm: 90,
    rarity: "rare",
    baseValueCoins: 90,
    difficulty: 0.6,
    movementProfile: { speed: 0.48, acceleration: 0.54, directionChangeFrequency: 0.58, unpredictability: 0.42, fightDurationSeconds: 23 },
    acceptedBaitIds: ["minnow", "crayfish", "premium-minnow"],
    preferredLureIds: ["silver-spinner", "deep-diver"],
    availableLocationIds: ["pinewater-lake", "lake-greywater"],
  }),
  fish({
    id: "northern-pike",
    commonName: "Northern Pike",
    scientificName: "Esox lucius",
    description: "An aggressive freshwater predator that strikes near weeds and drop-offs.",
    habitat: "Shallow weeds, weedy edges, and deeper drop-offs.",
    nativeRange: "Freshwater systems across Ontario, the Great Lakes, and the northern hemisphere.",
    minimumWeightKg: 0.3,
    typicalWeightKg: 2.5,
    maximumWeightKg: 20,
    minimumLengthCm: 30,
    typicalLengthCm: 65,
    maximumLengthCm: 120,
    rarity: "rare",
    baseValueCoins: 120,
    difficulty: 0.72,
    movementProfile: { speed: 0.64, acceleration: 0.9, directionChangeFrequency: 0.46, unpredictability: 0.52, fightDurationSeconds: 27 },
    acceptedBaitIds: ["minnow", "premium-minnow"],
    preferredLureIds: ["silver-spinner", "deep-diver"],
    availableLocationIds: ["pinewater-lake", "lake-greywater"],
  }),
  fish({
    id: "channel-catfish",
    commonName: "Channel Catfish",
    scientificName: "Ictalurus punctatus",
    description: "A whiskered bottom-feeder that becomes especially active in warm water.",
    habitat: "Deep holes, soft bottoms, and slow-moving freshwater.",
    nativeRange: "Central and eastern North America, including introduced Great Lakes waters.",
    minimumWeightKg: 0.2,
    typicalWeightKg: 2,
    maximumWeightKg: 15,
    minimumLengthCm: 25,
    typicalLengthCm: 60,
    maximumLengthCm: 120,
    rarity: "uncommon",
    baseValueCoins: 55,
    difficulty: 0.52,
    movementProfile: { speed: 0.36, acceleration: 0.68, directionChangeFrequency: 0.22, unpredictability: 0.4, fightDurationSeconds: 25 },
    acceptedBaitIds: ["worm", "crayfish"],
    preferredLureIds: [],
    availableLocationIds: ["pinewater-lake"],
  }),
  fish({
    id: "lake-trout",
    commonName: "Lake Trout",
    scientificName: "Salvelinus namaycush",
    description: "A cold-water char that patrols deep, clear basins and steep contours.",
    habitat: "Deep, cold, well-oxygenated lake water.",
    nativeRange: "The Great Lakes and cold freshwater systems of northern North America.",
    minimumWeightKg: 0.5,
    typicalWeightKg: 3,
    maximumWeightKg: 15,
    minimumLengthCm: 35,
    typicalLengthCm: 60,
    maximumLengthCm: 100,
    rarity: "rare",
    baseValueCoins: 180,
    difficulty: 0.68,
    movementProfile: { speed: 0.52, acceleration: 0.5, directionChangeFrequency: 0.62, unpredictability: 0.46, fightDurationSeconds: 30 },
    acceptedBaitIds: ["minnow", "premium-minnow"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
  fish({
    id: "chinook-salmon",
    commonName: "Chinook Salmon",
    scientificName: "Oncorhynchus tshawytscha",
    description: "A powerful Great Lakes sport fish known for long, forceful runs.",
    habitat: "Open cold water and tributary approaches during seasonal runs.",
    nativeRange: "Pacific origin; introduced populations now inhabit the Great Lakes.",
    minimumWeightKg: 1,
    typicalWeightKg: 5,
    maximumWeightKg: 25,
    minimumLengthCm: 45,
    typicalLengthCm: 80,
    maximumLengthCm: 120,
    rarity: "rare",
    baseValueCoins: 260,
    difficulty: 0.8,
    movementProfile: { speed: 0.72, acceleration: 0.82, directionChangeFrequency: 0.52, unpredictability: 0.58, fightDurationSeconds: 35 },
    acceptedBaitIds: ["premium-minnow"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
  fish({
    id: "coho-salmon",
    commonName: "Coho Salmon",
    scientificName: "Oncorhynchus kisutch",
    description: "A fast, acrobatic salmon that turns a clean hookset into a lively fight.",
    habitat: "Cold open water and tributary approaches.",
    nativeRange: "Pacific origin; introduced populations now inhabit the Great Lakes.",
    minimumWeightKg: 0.8,
    typicalWeightKg: 3,
    maximumWeightKg: 12,
    minimumLengthCm: 40,
    typicalLengthCm: 65,
    maximumLengthCm: 100,
    rarity: "rare",
    baseValueCoins: 220,
    difficulty: 0.76,
    movementProfile: { speed: 0.78, acceleration: 0.74, directionChangeFrequency: 0.7, unpredictability: 0.54, fightDurationSeconds: 31 },
    acceptedBaitIds: ["premium-minnow"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
  fish({
    id: "muskellunge",
    commonName: "Muskellunge",
    scientificName: "Esox masquinongy",
    description: "A scarce apex predator whose size and power make every encounter consequential.",
    habitat: "Clear bays, weed edges, and large-lake structure.",
    nativeRange: "The Great Lakes basin and connected freshwater systems of eastern North America.",
    minimumWeightKg: 2,
    typicalWeightKg: 8,
    maximumWeightKg: 30,
    minimumLengthCm: 60,
    typicalLengthCm: 100,
    maximumLengthCm: 150,
    rarity: "legendary",
    baseValueCoins: 600,
    difficulty: 0.94,
    movementProfile: { speed: 0.86, acceleration: 0.96, directionChangeFrequency: 0.8, unpredictability: 0.72, fightDurationSeconds: 45 },
    acceptedBaitIds: ["premium-minnow"],
    preferredLureIds: ["deep-diver"],
    availableLocationIds: ["lake-greywater"],
    source: LAKE_ONTARIO_OBJECTIVES,
  }),
];

export const GAME_CATALOG: GameCatalog = { locations, boats, rods, lures, baits, fish: fishSpecies };
